version: 2.0 # use CircleCI 2.0
jobs: # a collection of steps  
  update-green:
    docker: 
      - image: circleci/node:10.16.3 
    steps: 
      - checkout 
      - run:
          name: update-green
          command: echo "I build only for development, green update here"
workflows:
  version: 2
  updateGreen:    
    jobs:
      - update-green:
          filters:
            branches:
              only:
                - updateGreen