version: 2.0 # use CircleCI 2.0
jobs: # a collection of steps  
  build_all: 
    docker: 
      - image: circleci/node:10.16.3 
      - image: mongo:4.2.0 
    steps:
      - checkout 
      - run:
          name: build-all-step
          command: echo "I build for all except dev and master"
  build_dev:
    docker: 
      - image: circleci/node:10.16.3 
      - image: mongo:4.2.0 
    steps: 
      - checkout 
      - run:
          name: build-dev-step
          command: echo "I build only for development, blue update here"
  build_master:
    docker: 
      - image: circleci/node:10.16.3 
      - image: mongo:4.2.0 
    steps: 
      - checkout 
      - run:
          name: build-master-step
          command: echo "I build only for master"
workflows:
  version: 2
  build_all:    
    jobs:
      - build_all:
          filters:
            branches:
              ignore:
                - development
                - master
  build_dev:    
    jobs:
      - build_dev:
          filters:
            branches:
              only:
                - development
  build_master:    
    jobs:
      - build_master:
          filters:
            branches:
              only:
                - master