jobs: # a collection of steps  
  build_all: 
    docker: 
      - image: circleci/node:10.16.3 
      - image: mongo:4.2.0 
    steps:
      - checkout 
      - run:
          name: build-all-step
          command: echo "I build for all except dev and master.."
          command: echo "build app and lint app and upload"
  build_dev:
    docker: 
      - image: circleci/node:10.16.3 
      - image: mongo:4.2.0 
    steps: 
      - checkout 
      - run:
          name: build-dev-step
          command: echo "I build only for development"
          command: echo "update dev only"
  build_master:
    docker: 
      - image: circleci/node:10.16.3 
      - image: mongo:4.2.0 
    steps: 
      - checkout 
      - run:
          name: build-master-step
          command: echo "I build only for master"
          command: echo "create EKS and initialise k8 here"
version: 2.1
workflows:
  build_all:    
    jobs:
      - build_all:
          filters:
            branches:
              ignore:
                - development
                - main
  build_dev:    
    jobs:
      - build_dev:
          filters:
            branches:
              only:
                - development
  build_master:    
    jobs:
      - build_master:
          filters:
            branches:
              only:
                - main