version: 2.0 # use CircleCI 2.0
jobs: # a collection of steps  
  testjob:
    docker: 
      - image: circleci/node:10.16.3 
    steps: 
      - checkout 
      - run:
          name: testjob
          command: echo "do i get called also"
          
  update-blue:
    docker: 
      - image: circleci/node:10.16.3 
    steps: 
      - checkout 
      - run:
          name: update-blue
          command: echo "I build only for development, blue update here"
workflows:
  version: 2
  updateBlue:    
    jobs:
      - testjob
      - update-blue:
          filters:
            branches:
              only:
                - updateBlue