jobs: # a collection of steps  
  initialize-clusters:
    docker: 
      - image: circleci/node:10.16.3 
    steps: 
      - checkout 
      - run:
          name: build-master-step
          command: echo "I build only for main branch.. deploy infra, initialize k8 first time."
version: 2.1
workflows:
  deploy-infra:    
    jobs:
      - initialize-clusters:
          filters:
            branches:
              only:
                - main